### ISSUE TITLE
Remove all references to deep in this library

### ISSUE THREAD

**Issue by MrPowers** [mrpowers-io/spark-fast-tests#72]
I just noticed that this code errors out in Scala 2.13!?

```
Array(1, 2, 3).deep == Array(1, 2, 3).deep
```

Here's the error message:

```
error: value deep is not a member of Array[Int]
```

`sameElements` still works in Scala 2.13, so `Array(1, 2, 3) sameElements Array(1, 2, 3)` is fine.

Spark 3 will support Scala 2.12.  Not sure when Scala 2.13 will be supported by Spark, but might as well proactively make this library as compatible as possible.

Should probably start compiling this library with Scala 2.13 to programatically make sure it stays compatible.

**Comment by SemyonSinchenko** [comment]
Because the library is already tested against 2.13 in CI I will close the issue as not planned.
